### ISSUE TITLE
Example in README.md will not compile

### ISSUE THREAD

**Issue by jftuga** [circa10a/go-aws-news#6]
I have place a fixed version here:

https://gist.github.com/jftuga/a4981031f03e1e2ef47c325c01fb3e9a

Your original version has a few compilation errors.

**Comment by circa10a** [comment]
Thanks @jftuga . The intention really wasn't for it work via copy/paste, but to show what it could do. I'm sure other folks will try the same, so thanks for your input. I've made a PR to resolve.
